---
cifmw_bm_agent_iso_http_port: 80
cifmw_bm_agent_installer_timeout: 7200
cifmw_bm_agent_openshift_version: "4.18.3"
cifmw_bm_agent_core_password: "redhat"
cifmw_bm_agent_live_debug: false
cifmw_bm_agent_vmedia_uefi_path: ""
cifmw_bm_agent_enable_usb_boot: true
cifmw_bm_agent_disabled_ifaces: []
