---
- name: Run tempest job
  vars:
    run_test_fw: tempest
    test_operator_config: "{{ _stage_test_vars.cifmw_test_operator_tempest_config | default(cifmw_test_operator_tempest_config) }}"
    test_operator_job_name: "{{ _test_operator_tempest_name }}-{{ _stage_vars.name }}"
    test_operator_kind_name: "{{ _test_operator_tempest_kind_name }}"
    test_operator_crd_name: "{{ _test_operator_tempest_crd_name }}"
    test_operator_workflow: "{{ _test_operator_tempest_workflow }}"
    test_operator_config_playbook: tempest-tests.yml
  ansible.builtin.include_tasks: run-test-operator-job.yml
