---
# Since Tobiko may include disruptive tests (faults), it is better to execute it at the end
- name: Run tobiko job
  vars:
    _test_operator_tobiko_namespace: "{{ _stage_test_vars.cifmw_test_operator_tobiko_namespace | default(cifmw_test_operator_tobiko_namespace) }}"
    _test_operator_tobiko_container: "{{ _stage_test_vars.cifmw_test_operator_tobiko_container | default(cifmw_test_operator_tobiko_container) }}"
    _test_operator_tobiko_image: "{{ _stage_test_vars.cifmw_test_operator_tobiko_image | default(cifmw_test_operator_tobiko_image) }}"
    _test_operator_tobiko_image_tag: "{{ _stage_test_vars.cifmw_test_operator_tobiko_image_tag | default(cifmw_test_operator_tobiko_image_tag) }}"
    _test_operator_tobiko_testenv: "{{ _stage_test_vars.cifmw_test_operator_tobiko_testenv | default(cifmw_test_operator_tobiko_testenv) }}"
    _test_operator_tobiko_version: "{{ _stage_test_vars.cifmw_test_operator_tobiko_version | default(cifmw_test_operator_tobiko_version) }}"
    _test_operator_tobiko_pytest_addopts: "{{ _stage_test_vars.cifmw_test_operator_tobiko_pytest_addopts | default(cifmw_test_operator_tobiko_pytest_addopts) }}"
    _test_operator_tobiko_prevent_create: "{{ _stage_test_vars.cifmw_test_operator_tobiko_prevent_create | default(cifmw_test_operator_tobiko_prevent_create) }}"
    _test_operator_tobiko_num_processes: "{{ _stage_test_vars.cifmw_test_operator_tobiko_num_processes | default(cifmw_test_operator_tobiko_num_processes) }}"
    _test_operator_tobiko_kubeconfig_secret: "{{ _stage_test_vars.cifmw_test_operator_tobiko_kubeconfig_secret | default(cifmw_test_operator_tobiko_kubeconfig_secret) }}"
    _test_operator_tobiko_override_conf: "{{ _stage_test_vars.cifmw_test_operator_tobiko_override_conf | default(cifmw_test_operator_tobiko_override_conf) }}"
    _test_operator_tobiko_ssh_keytype: "{{ _stage_test_vars.cifmw_test_operator_tobiko_ssh_keytype | default(cifmw_test_operator_tobiko_ssh_keytype) }}"
    _test_operator_tobiko_ssh_keysize: "{{ _stage_test_vars.cifmw_test_operator_tobiko_ssh_keysize | default(cifmw_test_operator_tobiko_ssh_keysize) }}"
    _test_operator_tobiko_network_attachments: "{{ _stage_test_vars.cifmw_test_operator_tobiko_network_attachments | default(cifmw_test_operator_tobiko_network_attachments) }}"
    _test_operator_tobiko_workflow: "{{ _stage_test_vars.cifmw_test_operator_tobiko_workflow | default(cifmw_test_operator_tobiko_workflow) }}"
    _test_operator_tobiko_registry: "{{ _stage_test_vars.cifmw_test_operator_tobiko_registry | default(cifmw_test_operator_tobiko_registry) }}"
    run_test_fw: tobiko
    test_operator_config: "{{ _stage_test_vars.cifmw_test_operator_tobiko_config | default(cifmw_test_operator_tobiko_config) }}"
    test_operator_job_name: "{{ _stage_test_vars.cifmw_test_operator_tobiko_name |  default(cifmw_test_operator_tobiko_name) }}-{{ _stage_vars.name }}"
    test_operator_kind_name: "{{ _stage_test_vars.cifmw_test_operator_tobiko_kind_name | default(cifmw_test_operator_tobiko_kind_name) }}"
    test_operator_crd_name: "{{ _stage_test_vars.cifmw_test_operator_tobiko_crd_name |  default(cifmw_test_operator_tobiko_crd_name) }}"
    test_operator_workflow: "{{ _stage_test_vars.cifmw_test_operator_tobiko_workflow |  default(cifmw_test_operator_tobiko_workflow) }}"
    test_operator_config_playbook: tobiko-tests.yml
  ansible.builtin.include_tasks: run-test-operator-job.yml
