---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
- name: Check if there were some OOMKill
  ansible.builtin.shell: >
    oc get events
    --all-namespaces
    --field-selector type=Warning
    --sort-by=.lastTimestamp |
    grep -i -E 'OOMKill|Killing.*out of memory|Pressure' >
     {{ cifmw_os_must_gather_output_log_dir }}/latest/OOMKill-events.log
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig | default(cifmw_os_cluster_info_kubeconfig) }}"
  ignore_errors: true # noqa: ignore-errors
