---
- name: Run build_push_container role
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  vars_files:
    - "{{ playbook_dir }}/groups_vars/all.yml"
  tasks:
    - name: Run build_push_container role
      ansible.builtin.include_role:
        name: build_push_container
