---
# defaults file for federation
#
cifmw_ipa_namespace: ipa
cifmw_ipa_realm: openstack
cifmw_ipa_admin_username: admin
cifmw_ipa_admin_password: nomoresecrets
cifmw_ipa_user_password: nomoresecrets
cifmw_ipa_testgroup_name: kctestgroup
cifmw_ipa_client_id: rhoso
cifmw_ipa_client_secret: COX8bmlKAWn56XCGMrKQJj7dgHNAOl6f
cifmw_ipa_url_validate_certs: false
cifmw_ipa_run_osp_cmd_namespace: openstack
cifmw_ipa_domain: REDHAT
cifmw_ipa_IdpName: kcIDP
cifmw_ipa_remote_id: '{{ cifmw_ipa_keycloak_url }}/auth/realms/{{ cifmw_ipa_keycloak_realm }}'
cifmw_ipa_project_name: SSOproject
cifmw_ipa_group_name: SSOgroup
cifmw_ipa_mapping_name: SSOmap
cifmw_ipa_rules_file: rules.json
cifmw_ipa_clame_id: OIDC-preferred_username
