---
# defaults file for federation
#
cifmw_ipa_namespace: ipa
cifmw_ipa_realm: openstack
cifmw_ipa_admin_username: admin
cifmw_ipa_admin_password: nomoresecrets
cifmw_ipa_user_password: nomoresecrets
cifmw_ipa_url_validate_certs: false
cifmw_ipa_run_osp_cmd_namespace: openstack
cifmw_ipa_domain: REDHAT
