---
- name: Add host to runtime inventory
  ansible.builtin.add_host:
    name: "{{ _full_host_name }}"
    groups: "{{ _group }}s"
    ansible_ssh_user: "{{ _ssh_user }}"
    ansible_host: "{{ _add_ansible_host | ternary(_ansible_host, omit) }}"
    vm_type: "{{ _group }}"

- name: Ensure group section exists
  ansible.builtin.lineinfile:
    path: "{{ cifmw_libvirt_manager_tmp_inv_file }}"
    create: true
    line: "[{{ _group }}s]"
    regexp: "^\\[{{ _group }}s\\]$"
    state: present
    mode: "0644"

- name: Append host under proper group
  ansible.builtin.lineinfile:
    path: "{{ cifmw_libvirt_manager_tmp_inv_file }}"
    insertafter: "^\\[{{ _group }}s\\]$"
    line: "{{ _ini_line }}"
    regexp: "^{{ _full_host_name | regex_escape() }} "

- name: daniel debug
  ansible.builtin.copy:
    content: |
      {{ _vm_type | default('vm_type') }}
      {{ _std_group | default('std_group') }}
      {{ _group | default('group') }}
      {{ _ocp_name | default('ocp_name') }}
      {{ _hostname | default('hostname') }}
      {{ _ssh_user | default('sshuser') }}
      {{ _add_ansible_host | default('add_ansible_host') }}
      {{ _ansible_host | default('ansible_host') }}
      {{ _full_host_name | default('fullhostname') }}
      {{ _ini_line | default('ini_line') }}
    dest: "{{ ansible_user_dir }}/{{ _ocp_name | default('test') }}"
