---
- name: Start vm
  community.libvirt.virt:
    name: "{{ vm }}"
    state: running
    uri: "qemu:///system"
  register: _vm_start
  retries: 5
  delay: 30
  until: _vm_start.result is not failed


