FROM {{ base_image }}
COPY ./{{ cifmw_fdp_update_container_images_repo_name }}.repo /etc/yum.repos.d/
RUN dnf update -y {{ cifmw_fdp_update_container_images_update_dnf_args }} {{ cifmw_fdp_update_container_images_target_package }}*
