---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# All variables intended for modification should be placed in this file.
# All variables within this role should have a prefix of "cifmw_openshift_adp"

# OADP operator
cifmw_openshift_adp_namespace: openshift-adp
cifmw_openshift_adp_channel: stable
cifmw_openshift_adp_enable_node_agent: true

# S3 backend (MinIO or other S3-compatible)
cifmw_openshift_adp_s3_namespace: minio
cifmw_openshift_adp_s3_bucket: velero
cifmw_openshift_adp_s3_region: minio
cifmw_openshift_adp_s3_prefix: rhoso
cifmw_openshift_adp_s3_force_path_style: true
cifmw_openshift_adp_s3_insecure_skip_tls: true
# cifmw_openshift_adp_s3_access_key: REQUIRED
# cifmw_openshift_adp_s3_secret_key: REQUIRED
