---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Collect metrics when the pmlogger service is running
  when:
    - ansible_facts.services['pmlogger.service'] is defined
    - ansible_facts.services['pmlogger.service']['state'] == 'running'
  block:
    - name: Fetch needed fact
      ansible.builtin.setup:
        gather_subset:
          - min
        filter:
          - ansible_hostname
      when: ansible_hostname is undefined

    - name: Collect the metrics from host
      ansible.builtin.command: >-
        pmrep
          --archive "{{ pcp_metrics_archive }}"
          --interval "{{ pcp_metrics_interval }}"
          --timestamps
          "{{ pcp_metrics_metricspec }}"
      register: _pcp_metrics_pmrep
      changed_when: false

      # TODO: save to file
    - name: Show collected metrics
      ansible.builtin.debug:
        msg: "{{ _pcp_metrics_pmrep.stdout }}"

      # TODO: produce a plot?
