---
- name: Setup PCP
  include_role:
    name: "{{ role_name }}"
    tasks_from: setup
  when: pcp_metrics_setup | bool

- name: Gather mertrics
  include_role:
    name: "{{ role_name }}"
    tasks_from: gather
  when: pcp_metrics_gather | bool
