---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Obtain IPs whose routes need to be added to the undercloud (bgp)
  ansible.builtin.getent:
    database: ahosts
    key: "{{ item }}"
  register: _current_vm_getent
  loop:
    - registry.redhat.io
    - cdn.redhat.com
    - access.redhat.com
    - cdn01.quay.io

- name: Accumulate IPs from this VM
  ansible.builtin.set_fact:
    _accumulated_ips: >-
      {{
        _accumulated_ips | default([]) +
        (
          _current_vm_getent.results |
          map(attribute='ansible_facts.getent_ahosts') |
          map('dict2items') |
          flatten |
          map(attribute='key') |
          reject('match', '.*:.*') |
          list
        )
      }}
