cifmw_repo_setup_os_release: 'centos'
cifmw_repo_setup_dist_major_version: 10
cifmw_repo_setup_branch: master
cifmw_repo_setup_promotion: current
# DLRN current keep changing, causes 404 url not found
cifmw_repo_setup_dlrn_hash_tag: ''
