---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.
# All variables within this role should have a prefix of "cifmw_rally"
cifmw_rally_artifacts_basedir: "{{ cifmw_basedir }}/tests/rally"
cifmw_rally_registry: "quay.io"
cifmw_rally_namespace: "airshipit"
cifmw_rally_container: "xrally-openstack"
cifmw_rally_image: "{{ cifmw_rally_registry }}/{{ cifmw_rally_namespace }}/{{ cifmw_rally_container }}"
cifmw_rally_image_tag: "3.0.0"
cifmw_rally_dry_run: false
cifmw_rally_remove_container: true
cifmw_rally_fail_on_task_failure: true
cifmw_rally_deployment_name: "cifmw"
cifmw_rally_concurrency: 1
cifmw_rally_task_file: "default-task.yaml"
cifmw_rally_task_extra_args: ""
cifmw_rally_dns_servers:
  - "192.168.122.10"
