---
cifmw_install_yamls_vars:
  DEPLOY_DIR: "{{ cifmw_basedir }}/artifacts/edpm_compute" # used during Baremetal deployment
  INFRA_REPO: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/infra-operator"
  BMAAS_INSTANCE_MEMORY: 8192
  BMAAS_INSTANCE_VCPUS: 6
  BMAAS_INSTANCE_DISK_SIZE: 40
  DATAPLANE_GROWVOLS_ARGS: "/=8GB /tmp=1GB /home=1GB /var=8GB"

# edpm_deploy role vars
cifmw_edpm_deploy_baremetal: true
