---
- name: Ensure CRC is started
  ansible.builtin.command:
    cmd: >
      crc start {{ cifmw_helpers_crc_additional_params | default('') }}
  register: _crc_output
  ignore_errors: true  # noqa: ignore-errors

- name: Wait for cluster to stabilize after certificate renewal
  when: "'Kubelet serving certificate has expired' in _crc_output.stderr"
  ansible.builtin.command: >
    oc get nodes
    --kubeconfig={{ ansible_user_dir }}/.crc/machines/crc/kubeconfig
  register: _cluster_check
  until: _cluster_check.rc == 0
  retries: 150
  delay: 10
  changed_when: false
