---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- ansible.builtin.set_fact: output_file=test_run_result.out

- name: Delete old file if existing
  file:
    path: "{{ output_file }}"
    state: absent
  ignore_errors: true

- name: Create output file
  file:
    path: "{{ output_file }}"
    mode: "u=rw,g=r,o=r"
    state: touch

- name: Get keystone route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: keystone-public
    namespace: "{{ cifmw_ipa_run_osp_cmd_namespace }}"
  register: keystone_route


- name: Read ipa test user1 cloudrc template
  ansible.builtin.template:
    src: ipauser1.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'ipauser1' ] | path_join }}"
    mode: "0644"

- name: Copy ipa test user1 cloudrc file into pod
  kubernetes.core.k8s_cp:
    namespace: "{{ cifmw_ipa_run_osp_cmd_namespace }}"
    pod: openstackclient
    remote_path: "/home/cloud-admin/ipauser1"
    local_path: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'ipauser1' ] | path_join }}"


- name: RHELOSP-53684 - Security - List IPA ldap users
  vars:
    _osp_cmd: "openstack user list --domain REDHAT"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53684 - Security - List IPA ldap users - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53684=passed"
  when: "'ipauser1' in ipa_run_osc_cmd.stdout and 'ipauser2' in ipa_run_osc_cmd.stdout and 'ipauser3' in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53684 - Security - List IPA ldap users - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53684=failed"
  when: "'ipauser1' not in ipa_run_osc_cmd.stdout and 'ipauser2' not in ipa_run_osc_cmd.stdout and 'ipauser3' not in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53685 - Security - List IPA ldap groups
  vars:
    _osp_cmd: "openstack group list --domain REDHAT"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53685 - Security - List IPA ldap groups - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53685=passed"
  when: "'grp-openstack' in ipa_run_osc_cmd.stdout and 'grp-openstack-admin' in ipa_run_osc_cmd.stdout and 'grp-openstack-demo' in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53685 - Security - List IPA ldap groups - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53685=failed"
  when: "'grp-openstack' not in ipa_run_osc_cmd.stdout and 'grp-openstack-admin' not in ipa_run_osc_cmd.stdout and 'grp-openstack-demo' not in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53932 - Security - Check ipauser1 in ldap group grp-openstack-admin
  vars:
    _osp_cmd: "openstack group contains user --group-domain REDHAT --user-domain REDHAT grp-openstack-admin ipauser1"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53932 - Security - Check ipauser1 in ldap group grp-openstack-admin - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53932=passed"
  when: "'ipauser1 in group grp-openstack-admin' in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53932 - Security - Check ipauser1 in ldap group grp-openstack-admin - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53932=failed"
  when: "'ipauser1 in group grp-openstack-admin' not in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53933 - Security - Check ipauser2 in ldap group grp-openstack-demo
  vars:
    _osp_cmd: "openstack group contains user --group-domain REDHAT --user-domain REDHAT grp-openstack-demo ipauser2"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53933 - Security - Check ipauser2 in ldap group grp-openstack-demo - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53933=passed"
  when: "'ipauser2 in group grp-openstack-demo' in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53933 - Security - Check ipauser2 in ldap group grp-openstack-demo - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53933=failed"
  when: "'ipauser2 in group grp-openstack-demo' not in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53934 - Security - Check ipauser3 ldap in group grp-openstack
  vars:
    _osp_cmd: "openstack group contains user --group-domain REDHAT --user-domain REDHAT grp-openstack ipauser3"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53934 - Security - Check ipauser3 in ldap group grp-openstack - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53934=passed"
  when: "'ipauser3 in group grp-openstack' in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: RHELOSP-53934 - Security - Check ipauser3 in ldap group grp-openstack - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53934=failed"
  when: "'ipauser3 in group grp-openstack' not in ipa_run_osc_cmd.stdout"
  ignore_errors: true

- name: Template get-token.sh script
  ansible.builtin.template:
    src: get-token.sh.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'get-token.sh' ] | path_join }}"
    mode: "0755"

- name: Copy get-token.sh script into openstackclient pod
  kubernetes.core.k8s_cp:
    namespace: "{{ cifmw_ipa_run_osp_cmd_namespace }}"
    pod: openstackclient
    remote_path: "/home/cloud-admin/get-token.sh"
    local_path: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'get-token.sh' ] | path_join }}"

- name: RHELOSP-53935 - Security - Get token with ipauser1 user
  vars:
    _osp_cmd: "/home/cloud-admin/get-token.sh ipauser1"
  ansible.builtin.include_tasks: run_osp_cmd.yml

- name: RHELOSP-53935 - Security - Get token with ipauser1 user - success
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53935=passed"
  when: ipa_run_osc_cmd.stdout|length >= 180
  ignore_errors: true

- name: RHELOSP-53935 - Security - Get token with ipauser1 user - failed
  lineinfile:
    path: "{{ output_file }}"
    line: "RHELOSP-53935=failed"
  when: ipa_run_osc_cmd.stdout|length < 180
  ignore_errors: true
