FROM registry.access.redhat.com/ubi9/ubi-init

RUN curl -o /etc/yum.repos.d/delorean.repo https://trunk.rdoproject.org/centos9-master/current/delorean.repo && \
    dnf upgrade -y && \
    dnf -y install sudo python3 python3-libselinux selinux-policy git python3-pip && \
    git clone https://github.com/openstack-k8s-operators/repo-setup && \
    cd repo-setup && \
    pip install -r requirements.txt && \
    python3 setup.py install && \
    dnf clean all -y

CMD [ '/sbin/init' ]
