stacks:
  - stackname: overcloud
    network_data_file: "network_data.yaml.j2"
    vips_data_file: "vips_data_overcloud.yaml"
    stack_nodes:
      - osp-controllers
  - stackname: cell1
    network_data_file: "network_data.yaml.j2"
    vips_data_file: "vips_data_cell1.yaml"
    stack_nodes:
      - cell1-osp-computes
      - cell1-osp-controllers
  - stackname: cell2
    network_data_file: "network_data.yaml.j2"
    vips_data_file: "vips_data_cell2.yaml"
    stack_nodes:
      - cell2-osp-computes
      - cell2-osp-controllers

expected_nodes:
  overcloud:
    - osp-controller-uni05epsilon-0
  cell1:
    - cell1-osp-compute-uni05epsilon-0
    - cell1-osp-controller-uni05epsilon-0
  cell2:
    - cell2-osp-compute-uni05epsilon-0
    - cell2-osp-controller-uni05epsilon-0

cifmw_adoption_osp_deploy_scenario:
  stacks:
    - stackname: overcloud
    - stackname: cell1
    - stackname: cell2
  cloud_domain: example.com
  network_tripleo_network_map:
    ctlplane: ctlplane
    internalapi: internalapi
    storage: storage
    tenant: tenant
  hostname_groups_map:
    cell1-osp-computes: cell1-novacompute
    cell1-osp-controllers: cell1-controller
    cell2-osp-computes: cell2-novacompute
    cell2-osp-controllers: cell2-controller
    osp-controllers: overcloud-controller
  roles_groups_map:
    # map ansible groups to tripleo Role names
    osp-controllers: Controller
    cell1-osp-controllers: CellController
    cell2-osp-controllers: CellController

# Vars to simulate playbook execution context
_vm_groups:
  cell1-osp-computes:
    - cell1-osp-compute-uni05epsilon-0
  cell1-osp-controllers:
    - cell1-osp-controller-uni05epsilon-0
  cell2-osp-computes:
    - cell2-osp-compute-uni05epsilon-0
  cell2-osp-controllers:
    - cell2-osp-controller-uni05epsilon-0
  controllers:
    - controller-0
  ocps:
    - ocp-master-0
    - ocp-master-1
    - ocp-master-2
  osp-controllers:
    - osp-controller-uni05epsilon-0
  osp-underclouds:
    - osp-undercloud-uni05epsilon-0

_stack_names:
  - overcloud
  - cell1
  - cell2

_default_cell_name: default

# Expected edpm_nodes structure for multi-cell scenario
expected_edpm_nodes:
  cell1:
    - cell1-osp-compute-uni05epsilon-0
  cell2:
    - cell2-osp-compute-uni05epsilon-0

cifmw_adoption_osp_deploy_adoption_vars_exclude_nets: []

# Variables needed by template
_controller_1_internalapi_ip: 172.17.0.100
_compute_1_name: cell1-osp-compute-uni05epsilon-0
_compute_1_ip: 192.168.122.110
_undercloud_ip: 192.168.122.1

cifmw_networking_env_definition:
  networks:
    ctlplane:
      dns_v4:
        - 8.8.8.8
  instances:
    osp-controller-uni05epsilon-0:
      networks:
        ctlplane:
          ip_v4: 192.168.122.100
        internalapi:
          ip_v4: 172.17.0.100
    cell1-osp-compute-uni05epsilon-0:
      networks:
        ctlplane:
          ip_v4: 192.168.122.110
        internalapi:
          ip_v4: 172.17.0.110
    cell2-osp-compute-uni05epsilon-0:
      networks:
        ctlplane:
          ip_v4: 192.168.122.120
        internalapi:
          ip_v4: 172.17.0.120
