FROM {{ cifmw_pkg_build_ctx_baseimg }}

RUN dnf upgrade --refresh -y && dnf install -y git python3-pip ansible-core sudo
RUN groupadd mock
RUN usermod -a -G mock root

# Prepare for DLRN
RUN dnf install -y createrepo gcc redhat-rpm-config rpmdevtools httpd \
  libffi-devel openssl-devel yum-utils rsync rpm-build rpmdevtools sqlite \
  python3-libselinux

RUN ansible-galaxy collection install --force community.general ansible.posix
COPY ./build_openstack_packages /root/roles/build_openstack_packages

WORKDIR /root
