- name: Create the sushy-emulator namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
    api_key: "{{ cifmw_openshift_token | default(omit)}}"
    context: "{{ cifmw_openshift_context | default(omit) }}"
    name: "{{ cifmw_sushy_emulator_namespace }}"
    kind: Namespace
    state: present

- name: Apply Sushy Emulator resources
  kubernetes.core.k8s:
    kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
    api_key: "{{ cifmw_openshift_token | default(omit)}}"
    context: "{{ cifmw_openshift_context | default(omit) }}"
    name: "{{ cifmw_sushy_emulator_namespace }}"
    state: present
    src: "{{ (cifmw_sushy_emulator_resource_directory, item+'.yaml') | path_join }}"
  with_items:
    - secret
    - configmap
    - pod
    - service
    - route
