---
# Mainly used to override the defaults set in .config/molecule/
# By default, it uses the "config_podman.yml" - locally, it will use
# "config_local.yml" in CI.
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml

log: true

provisioner:
  name: ansible
  log: true
