---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Force SNO mode for devscripts
  ansible.builtin.set_fact:
    cifmw_devscripts_sno: true

- name: Ensure secret dir exists
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
  loop:
    - "{{ cifmw_manage_secrets_citoken_file }}"
    - "{{ cifmw_manage_secrets_pullsecret_file }}"

- name: Copy required content - ci token
  no_log: true
  ansible.builtin.copy:
    content: "{{ cifmw_manage_secrets_citoken_content }}"
    dest: "{{ cifmw_manage_secrets_citoken_file }}"

- name: Copy required content - pull secret
  no_log: true
  ansible.builtin.copy:
    content: "{{ cifmw_manage_secrets_pullsecret_content }}"
    dest: "{{ cifmw_manage_secrets_pullsecret_file }}"

- name: Install required packages
  ansible.builtin.include_role:
    name: ci_setup
    tasks_from: packages.yml

- name: Deploy VBMC, run devscripts SNO, and clean up
  block:
    - name: Ensure VBMC is present
      ansible.builtin.import_role:
        name: "virtualbmc"

    - name: Run devscripts role
      ansible.builtin.include_role:
        name: "devscripts"

#  always:
#    - name: Remove temporary virtualbmc instance
#      ansible.builtin.include_role:
#        name: "virtualbmc"
#        tasks_from: "cleanup.yml"
