---
- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: "0750"

- name: Copy devscripts kubeconfig to .kube
  ansible.builtin.copy:
    src: "{{ cifmw_devscripts_sno_repo_dir }}/ocp/ocp/auth/kubeconfig"
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: true
    mode: "0640"
