---
- name: Re-assign devscripts_sno vars with devscripts role vars
  ansible.builtin.set_fact:
    cifmw_devscripts_repo_dir: "{{ cifmw_devscripts_sno_repo_dir }}"
    cifmw_devscripts_data_dir: "{{ cifmw_devscripts_sno_data_dir }}"
    cifmw_devscripts_artifacts_dir: "{{ cifmw_devscripts_sno_artifacts_dir }}"
    cifmw_devscripts_installer_timeout: "{{ cifmw_devscripts_sno_installer_timeout }}"

- name: Ensure secret dir exists
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ cifmw_manage_secrets_citoken_file }}"
    - "{{ cifmw_manage_secrets_pullsecret_file }}"

- name: Copy required content - ci token
  no_log: true
  ansible.builtin.copy:
    content: "{{ cifmw_manage_secrets_citoken_content }}"
    dest: "{{ cifmw_manage_secrets_citoken_file }}"
    mode: "0640"

- name: Copy required content - pull secret
  no_log: true
  ansible.builtin.copy:
    content: "{{ cifmw_manage_secrets_pullsecret_content }}"
    dest: "{{ cifmw_manage_secrets_pullsecret_file }}"
    mode: "0640"

- name: Install required packages
  ansible.builtin.include_role:
    name: ci_setup
    tasks_from: packages.yml
