---
- name: Run devscripts role - build config
  ansible.builtin.include_role:
    name: devscripts
    tasks_from: build_config.yml

- name: Run devscripts role - 100_pre.yml
  ansible.builtin.include_role:
    name: devscripts
    tasks_from: 100_pre.yml

- name: Run devscripts make agent
  cifmw.general.ci_script:
    chdir: "{{ cifmw_devscripts_sno_repo_dir }}"
    output_dir: "{{ cifmw_devscripts_sno_artifacts_dir }}"
    script: "timeout {{ cifmw_devscripts_sno_installer_timeout }} make agent"
