#!/bin/bash
# Copyright 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# NetworkManager requires files to not be readable by group and other
chmod 0600 /etc/NetworkManager/conf.d/nat64-manage.conf
chmod 0600 /etc/NetworkManager/system-connections/nat64.nmconnection

# Make sure configure-nat64 script is executable
chmod 0755 /usr/local/sbin/configure-nat64
