---
- name: "Run stage {{ _stage_vars.name }}"
  ansible.builtin.debug:
    msg: "Run stage {{ _stage_vars.name }}"

- name: "Call pre stage hooks for test operator stage {{ _stage_vars.name }}"
  when:
    - not cifmw_test_operator_dry_run | bool
    - _stage_vars.pre_test_stage_hooks is defined
  vars:
    step: pre_test_hooks
    hooks: "{{ _stage_vars.pre_test_stage_hooks }}"
  ansible.builtin.import_role:
    name: run_hook

- name: Load stage variables
  ansible.builtin.include_tasks: load-stage-vars.yml

- name: "Call runner {{ _stage_vars.type }}"
  ansible.builtin.include_tasks: "runners/{{ _stage_vars.type }}_runner.yml"

- name: "Call post stage hooks for test operator stage {{ _stage_vars.name }}"
  when:
    - not cifmw_test_operator_dry_run | bool
    - _stage_vars.post_test_stage_hooks is defined
  vars:
    step: post_test_hooks
    hooks: "{{ _stage_vars.post_test_stage_hooks }}"
  ansible.builtin.import_role:
    name: run_hook
