---
- name: Update container images for namespace {{ cifmw_update_containers_namespace }}
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: "Update containers in {{ cifmw_update_containers_namespace }}"
      ansible.builtin.include_role:
        name: update_containers
