---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Read federation rhsso operator template
  ansible.builtin.template:
    src: rhsso-operator-olm.yaml.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'rhsso-operator-olm.yaml' ] | path_join }}"

- name: Install federation rhsso operator
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: "oc apply -f {{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'rhsso-operator-olm.yaml' ] | path_join }}"

- name: Approve rhsso operator install plan
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: "oc patch installplan
      $(oc get ip -n {{ cifmw_federation_keycloak_namespace }}
      -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}')
      -n {{ cifmw_federation_keycloak_namespace }} 
      --type merge --patch '{\"spec\":{\"approved\":true}}'"

- name: Add sso admin user secret
  kubernetes.core.k8s:
    kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: credential-sso
        namespace: "{{ cifmw_federation_keycloak_namespace }}"
      data:
        ADMIN_USERNAME: "{{ cifmw_federation_keycloak_admin_username }}"
        ADMIN_PASSWORD: "{{ cifmw_federation_keycloak_admin_password }}"

- name: Read federation sso template
  ansible.builtin.template:
    src: sso.yaml.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'sso.yaml' ] | path_join }}"

- name: Install federation sso pod
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: "oc apply -f {{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'sso.yaml' ] | path_join }}"

- name: Add CRC IP address to hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars['crc'].ansible_host }} api.crc.testing
      {{ hostvars['crc'].ansible_host }} oauth-openshift.apps-crc.testing
      {{ hostvars['crc'].ansible_host }} sso-openstack.apps-crc.testing
  when: cifmw_federation_deploy_type == "crc"

- name: Wait for SSO pod to be avalable
  ansible.builtin.uri:
    url: "{{ cifmw_federation_keycloak_url }}"
    follow_redirects: none
    method: GET
    validate_certs: "{{ cifmw_federation_keycloak_url_validate_certs }}"
  register: _result
  until: _result.status == 200
  retries: 24 # wait at least 2 min for pod then fail
  delay: 5

- name: Get ingress operator CA cert
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: >-
      oc extract secret/router-ca --to={{ [ ansible_user_dir , 'ci-framework-data','tmp'] | path_join }} --keys=tls.crt -n openshift-ingress-operator --confirm

- name: Store ingress operator CA to file for openstackclient pod
  ansible.builtin.copy:
    src: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'tls.crt'] | path_join }}"
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'ingress-operator-ca.crt'] | path_join }}"
