---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Create kube directory for config (CRC compatibility)
  ansible.builtin.file:
    path: "{{ [ ansible_user_dir, '.kube' ] | path_join }}"
    state: directory
    mode: '0770'
  when: cifmw_federation_deploy_type == "crc"

- name: Link kubeconfig for compatibility (CRC)
  ansible.builtin.copy:
    src: "{{ [ ansible_user_dir, '.crc', 'machines', 'crc', 'kubeconfig' ] | path_join }}"
    dest: "{{ [ ansible_user_dir, '.kube', 'config' ] | path_join }}"
    mode: "0640"
  when: cifmw_federation_deploy_type == "crc"

- name: Create Keycloak namespace
  ansible.builtin.include_tasks: shared_tasks.yml
  vars:
    task_name: "Create namespace if not exists"
    namespace_name: "{{ cifmw_federation_keycloak_namespace }}"

- name: Read federation rhsso operator template
  ansible.builtin.template:
    src: rhsso-operator-olm.yaml.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'rhsso-operator-olm.yaml' ] | path_join }}"
    mode: "0644"

- name: Install federation rhsso operator
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: "oc apply -f {{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'rhsso-operator-olm.yaml' ] | path_join }}"

- name: Wait for the rhsso install plan to be present
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
  register: ip_list
  until: >-
    {{
      ip_list.resources |
      map(attribute='metadata.labels') |
      select('match', '.*rhsso-operator.*')
    }}
  retries: 30
  delay: 40

- name: Approve rhsso operator install plan
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.shell: >-
    oc patch installplan
    $(oc get ip
    -o=jsonpath='{.items[].metadata.name}')
    --type merge --patch '{"spec":{"approved":true}}'

- name: Create SSO admin credentials secret
  ansible.builtin.include_tasks: shared_tasks.yml
  vars:
    task_name: "Create Keycloak admin credentials secret"

- name: Read federation sso template
  ansible.builtin.template:
    src: sso.yaml.j2
    dest: "{{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'sso.yaml' ] | path_join }}"
    mode: "0644"

- name: Install federation sso pod
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: "oc apply -n {{ cifmw_federation_keycloak_namespace }} -f {{ [ ansible_user_dir, 'ci-framework-data', 'tmp', 'sso.yaml' ] | path_join }}"

- name: Add CRC IP address to hosts (CRC only)
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars['crc'].ansible_host }} api.crc.testing
      {{ hostvars['crc'].ansible_host }} oauth-openshift.apps-crc.testing
      {{ hostvars['crc'].ansible_host }} keycloak-openstack.apps-crc.testing
  when: cifmw_federation_deploy_type == "crc"

- name: Wait for SSO pod to be available
  ansible.builtin.include_tasks: shared_tasks.yml
  vars:
    task_name: "Wait for service to be available"
    service_url: "{{ cifmw_federation_keycloak_url }}"
    service_wait_retries: 48
    service_wait_delay: 5

- name: Extract and store ingress operator CA certificate
  ansible.builtin.include_tasks: shared_tasks.yml
  vars:
    task_name: "Get ingress operator CA certificate"
