---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Create Keycloak realms
  community.general.keycloak_realm:
    auth_client_id: admin-cli
    validate_certs: "{{ cifmw_federation_keycloak_url_validate_certs }}"
    auth_keycloak_url: "{{ cifmw_federation_keycloak_url }}/auth"
    auth_realm: master
    auth_username: "{{ cifmw_federation_keycloak_admin_username }}"
    auth_password: "{{ cifmw_federation_keycloak_admin_password }}"
    id: "{{ item.name }}"
    realm: "{{ item.name }}"
    enabled: true
    state: present
  loop: "{{ cifmw_federation_realms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create Keycloak clients
  community.general.keycloak_client:
    auth_client_id: admin-cli
    validate_certs: "{{ cifmw_federation_keycloak_url_validate_certs }}"
    auth_keycloak_url: "{{ cifmw_federation_keycloak_url }}/auth"
    auth_realm: master
    auth_username: "{{ cifmw_federation_keycloak_admin_username }}"
    auth_password: "{{ cifmw_federation_keycloak_admin_password }}"
    state: present
    realm: "{{ item.name }}"
    client_id: "{{ item.client_id }}"
    name: 'RHOSO Client for {{ item.name }}'
    description: 'RHOSO client for keystone federation in {{ item.name }} realm'
    root_url: "{{ cifmw_federation_keystone_url }}"
    admin_url: "{{ cifmw_federation_keystone_url }}"
    base_url: '/dashboard/project'
    enabled: true
    client_authenticator_type: client-secret
    secret: "{{ item.client_secret }}"
    redirect_uris:
      - "{{ cifmw_federation_keystone_url }}/v3/auth/OS-FEDERATION/identity_providers/{{ item.idp_name }}/protocols/openid/websso/"
      - "{{ cifmw_federation_keystone_url }}/v3/auth/OS-FEDERATION/websso/openid"
      - "{{ cifmw_federation_keystone_url }}/v3/redirect_uri"
      - "{{ cifmw_federation_horizon_url }}/dashboard/auth/websso/"
    web_origins:
      - "{{ cifmw_federation_keystone_url }}"
      - "{{ cifmw_federation_horizon_url }}"
    bearer_only: false
    public_client: false
    implicit_flow_enabled: true
    protocol: openid-connect
  loop: "{{ cifmw_federation_realms }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create Keycloak groups
  community.general.keycloak_group:
    auth_client_id: admin-cli
    validate_certs: "{{ cifmw_federation_keycloak_url_validate_certs }}"
    auth_keycloak_url: "{{ cifmw_federation_keycloak_url }}/auth"
    auth_realm: master
    auth_username: "{{ cifmw_federation_keycloak_admin_username }}"
    auth_password: "{{ cifmw_federation_keycloak_admin_password }}"
    state: present
    name: "{{ user.group }}"
    realm: "{{ realm.name }}"
  loop: "{{ cifmw_federation_realms | subelements('test_users') }}"
  loop_control:
    loop_var: user
    label: "{{ user.1.group }} in {{ user.0.name }}"
  vars:
    realm: "{{ user.0 }}"

- name: Create Keycloak users
  community.general.keycloak_user:
    auth_client_id: admin-cli
    validate_certs: "{{ cifmw_federation_keycloak_url_validate_certs }}"
    auth_keycloak_url: "{{ cifmw_federation_keycloak_url }}/auth"
    auth_realm: master
    auth_username: "{{ cifmw_federation_keycloak_admin_username }}"
    auth_password: "{{ cifmw_federation_keycloak_admin_password }}"
    state: present
    realm: "{{ realm.name }}"
    username: "{{ user.1.username }}"
    firstName: "{{ user.1.username | title }}"
    lastName: "User"
    email: "{{ user.1.username }}@{{ realm.name }}.openstack.lab"
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: "{{ user.1.password }}"
        temporary: false
    groups:
      - name: "{{ user.1.group }}"
        state: present
  loop: "{{ cifmw_federation_realms | subelements('test_users') }}"
  loop_control:
    loop_var: user
    label: "{{ user.1.username }} in {{ user.0.name }}"
  vars:
    realm: "{{ user.0 }}"
