---
- name: "Checking if file exists {{ secret_file }}"
  ansible.builtin.stat:
    path: "{{ secret_file }}"
  register: _current_file

- name: Add secret file into cifmw_deploy_architecture_args when exists
  when: _current_file.stat.exists
  ansible.builtin.set_fact:
    cifmw_deploy_architecture_args: >
      {{ cifmw_deploy_architecture_args | default('') }}
      -e @{{ secret_file }}
