---
# NOTE(dpawlik): Earlier, our idea was to dump vars as
# it is roles/cifmw_setup/tasks/bootstrap.yml and read it,
# then dump it and replace reproducer-variables.yml.
# Normally it make sense, but since we dump zuul_vars in
# run.yml, we don't need to make such combination, which is
# more safe - on making host variable dump, some variables
# might not be defined, so later we can have an issue like:
#     'cifmw_discovered_image_url' is undefined.

- name: Check if zuul_vars.yaml file is available
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/configs/zuul_vars.yaml"
  register: _current_zuul_vars

- name: Overwrite reproducer-variables.yml when ZIronic used
  when: _current_zuul_vars.stat.exists
  vars:
    temp_reproducer_var_path: /tmp/reproducer-variables.yml
    temp_merged_reproducer_var_path: /tmp/merged-reproducer-variables.yml
  block:
    - name: Slurp reproducer-variables.yml to hypervisor
      ansible.builtin.slurp:
        src: "{{ cifmw_basedir }}/parameters/reproducer-variables.yml"
      register: reproducer_original
      delegate_to: controller-0
      no_log: "{{ cifmw_nolog | default(true) | bool }}"

    - name: Create temp file reproducer-variables.yml on hypervisor
      ansible.builtin.copy:
        content: "{{ reproducer_original.content | b64decode }}"
        dest: "{{ temp_reproducer_var_path }}"
        mode: "0664"
      no_log: "{{ cifmw_nolog | default(true) | bool }}"

    - name: Copy merge yamls script
      become: true
      ansible.builtin.copy:
        src: merge_yaml_override.py
        dest: /usr/local/bin/merge_yaml_override
        mode: "0755"

    - name: Execute merge script
      ansible.builtin.shell: >
        python3 /usr/local/bin/merge_yaml_override
        {{ temp_reproducer_var_path }}
        {{ ansible_user_dir }}/configs/zuul_vars.yaml >
        {{ temp_merged_reproducer_var_path }}
      no_log: "{{ cifmw_nolog | default(true) | bool }}"

    - name: Slurp merged reproducer-variables.yml from hypervisor
      ansible.builtin.slurp:
        src: "{{ temp_merged_reproducer_var_path }}"
      register: merged_reproducer_slurp
      no_log: "{{ cifmw_nolog | default(true) | bool }}"

    - name: Write back merged reproducer-variables.yml
      ansible.builtin.copy:
        content: "{{ merged_reproducer_slurp.content | b64decode }}"
        dest: "{{ cifmw_basedir }}/parameters/reproducer-variables.yml"
        mode: "0664"
        backup: true
      no_log: "{{ cifmw_nolog | default(true) | bool }}"
      delegate_to: controller-0

    - name: Overwrite custom-params.yml
      ansible.builtin.copy:
        content: "{{ merged_reproducer_slurp.content | b64decode }}"
        dest: "{{ cifmw_basedir }}/artifacts/parameters/custom-params.yml"
        mode: "0664"
      no_log: "{{ cifmw_nolog | default(true) | bool }}"
      delegate_to: controller-0
