---
# No log in that file are necessary and it should not use: cifmw_nolog var.
- name: Slurp full pull-secret from secrets dir
  ansible.builtin.slurp:
    src: "{{ ansible_user_dir }}/secrets/pull_secret.json"
  register: _full_pull_secret
  delegate_to: hypervisor
  no_log: true

- name: Get current cluster pull-secret
  kubernetes.core.k8s_info:
    kubeconfig: "{{ cifmw_openshift_kubeconfig | default(ansible_user_dir ~ '/.kube/config') }}"
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: _cluster_pull_secret
  delegate_to: controller-0
  no_log: true

- name: Merge and update cluster pull-secret
  vars:
    _full_auths: "{{ (_full_pull_secret.content | b64decode | from_json).auths }}"
    _cluster_auths: "{{ (_cluster_pull_secret.resources[0].data['.dockerconfigjson'] | b64decode | from_json).auths }}"
    _merged:
      auths: "{{ _cluster_auths | combine(_full_auths, recursive=true) }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ cifmw_openshift_kubeconfig | default(ansible_user_dir ~ '/.kube/config') }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pull-secret
        namespace: openshift-config
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ _merged | to_json | b64encode }}"
  delegate_to: controller-0
  no_log: true
