---
- name: Synchronize src dir
  ansible.builtin.include_tasks:
    file: sync_src_dir.yml

# NOTE(dpawlik): After calling reproducer role using PreMetal tool,
# when the bootstrap phase has been completed, it generates a file
# "reproducer-variables.yml" that contains all variables done in the
# CI job. The problem here is, that "testing" phase might have other
# variables than what was in the bootstrap phase. It means, that
# we need to overwrite the variables with current CI job vars.
- name: Overwrite reproducer-variables.yml when PreMetal bootstrap
  ansible.builtin.include_tasks:
    file: overwrite_zuul_vars.yml

- name: Overwrite pull-secret.json and add missing registries
  ansible.builtin.include_tasks:
    file: overwrite_pull_secret.yml
