FROM registry.access.redhat.com/ubi9/ubi-init:latest
LABEL summary="Provides root image for openstack-k8s-operators projects in Prow" maintainer="CI Framework"

USER root
RUN dnf update -y && dnf install -y git python3-pip make gcc sudo && yum clean all
