FROM quay.io/centos/centos:stream9
LABEL summary="Lightweight image to build documentation and run pyspelling" \
      maintainer="CI Framework"

# Match the GitHub docs workflow (ubuntu-24.04 ships Python 3.12)
RUN dnf -y install dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf -y install --setopt=install_weak_deps=False --nodocs \
        python3.12 \
        python3.12-pip \
        make \
        git \
        aspell \
        aspell-en \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && ln -sf /usr/bin/python3.12 /usr/bin/python \
    && python3.12 -m pip install --no-cache-dir pyspelling mkdocs-pymdownx-material-extras

WORKDIR /opt/sources
CMD ["make", "spelling"]
