FROM localhost/cfwm-build:latest
USER root
ENV USE_VENV=no
ENV MOLECULE_CONFIG=.config/molecule/config_local.yml

COPY ../ /opt/sources
RUN find /opt/sources -type d -exec chmod g+rwx {} \;
RUN find /opt/sources -type f -exec chmod g+rw {} \;
WORKDIR /opt/sources
RUN git config core.fileMode false
RUN /usr/bin/make setup_molecule USE_VENV=${USE_VENV}
CMD /usr/bin/make help
