FROM registry.access.redhat.com/ubi9/ubi-init:latest
USER root
ENV USE_VENV=no

RUN dnf update -y && dnf install -y git python3-pip make gcc sudo && yum clean all

COPY ../ /opt/sources
RUN find /opt/sources -type d -exec chmod g+rwx {} \;
RUN find /opt/sources -type f -exec chmod g+rw {} \;
WORKDIR /opt/sources
RUN git config core.fileMode false
RUN /usr/bin/make setup_molecule USE_VENV=${USE_VENV}
CMD /usr/bin/make help
