FROM quay.io/centos/centos:stream9
LABEL summary="Provides root image for openstack-k8s-operators projects in Prow" maintainer="CI Framework"

USER root
# workaround for RHBZ#2184640
RUN sed -i 's/gpgcheck=1/gpgcheck=0/' /etc/yum.repos.d/*.repo
RUN dnf update -y && dnf install -y git python3-pip make gcc sudo && yum clean all
