FROM localhost/cifmw-build:latest
USER root
ENV USE_VENV=no
ENV MOLECULE_CONFIG=.config/molecule/config_local.yml

RUN adduser -d / -M prow
RUN echo "prow ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/prow

COPY ../ /opt/sources
RUN chown -R prow: /opt/sources
WORKDIR /opt/sources
RUN find . -type d -exec chmod g+rwx {} \;
RUN find . -type f -exec chmod g+rw {} \;
RUN /usr/bin/make setup_molecule USE_VENV=${USE_VENV}

USER prow
RUN git config core.fileMode false
CMD /usr/bin/make help
