#!/bin/bash
set -xe

PROJECT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))/../"
cp ${PROJECT_DIR}/ci/templates/jobs-init.yaml ${PROJECT_DIR}/zuul.d/jobs.yaml; \
cp ${PROJECT_DIR}/ci/templates/projects.yaml ${PROJECT_DIR}/zuul.d/projects.yaml; \
for role in ${PROJECT_DIR}/ci_framework/roles/* ; do \
    role=`basename ${role}`; \
    sed "s/ROLE/${role}/" ${PROJECT_DIR}/ci/templates/jobs.yaml >> ${PROJECT_DIR}/zuul.d/jobs.yaml; \
    echo "        - cifmw-molecule-${role}" >> ${PROJECT_DIR}/zuul.d/projects.yaml; \
done
