#!/usr/bin/env bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


## Shell Opts ----------------------------------------------------------------

set -o pipefail
set -xeuo

CIFMW_REPO_PATH=/home/zuul/src/ci-framework

if [[ ! -d "$CIFMW_REPO_PATH" ]]; then
    git clone https://github.com/openstack-k8s-operators/ci-framework "$CIFMW_REPO_PATH"
fi

if [[ ! -d /home/zuul/src/install_yamls ]]; then
    git clone https://github.com/openstack-k8s-operators/install_yamls /home/zuul/src/install_yamls
fi

pushd "$CIFMW_REPO_PATH"
pip install --upgrade pip setuptools bindep
pip install -r requirements.txt -r ansible-requirements.txt
./scripts/bindep-install
ansible-galaxy collection install -r requirements.yml
