#!/usr/bin/env bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


## Shell Opts ----------------------------------------------------------------

set -o pipefail
set -xeuo

## Vars ----------------------------------------------------------------------

export PROJECT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))/../"
export ROLE_NAME="${ROLE_NAME:-$1}"

# Run local test
(test -d ${PROJECT_DIR}ci_framework/roles/ || (echo 'No such directory: ${PROJECT_DIR}ci_framework/roles/' && exit 1) ) || exit 1
(test -d "${PROJECT_DIR}ci_framework/roles/${ROLE_NAME}" || (echo "No such role: ${ROLE_NAME}" && exit 1)) || exit 1
pushd "${PROJECT_DIR}ci_framework/roles/${ROLE_NAME}"
case ${USE_VENV:-yes} in
    'y|yes|true')
        ${HOME}/test-python/bin/molecule -c "${PROJECT_DIR}.config/molecule/config_podman.yaml" test
        ;;
    *)
        molecule -c "${PROJECT_DIR}.config/molecule/config_podman.yaml" test
        ;;
esac
popd
