#!/usr/bin/env bash
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


## Shell Opts ----------------------------------------------------------------
set -o pipefail
set -xeuo

## Vars ----------------------------------------------------------------------
export PROJECT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))/../"
# NOTE(cloudnull): Disable ansible compat check, caters to the case where
#                  system ansible may be installed.
export ANSIBLE_SKIP_CONFLICT_CHECK=1
PIP='pip'
GALAXY="ansible-galaxy"
COLLECTION_PATH="/usr/share/ansible/collections"
USE_VENV=${USE_VENV:-yes}
PYTHON_EXEC=$(command -v python3 || command -v python)

case ${USE_VENV} in
    y|yes|true)
        PIP="${HOME}/test-python/bin/pip"
        USE_VENV='yes'
        GALAXY="${HOME}/test-python/bin/ansible-galaxy"
        COLLECTION_PATH="${HOME}/.ansible/collections/ansible_collections/"
        ${PYTHON_EXEC} -m venv -h 2>&1>/dev/null || sudo "${RHT_PKG_MGR}" install -y python*-virtualenv
        ;;
    n|no|false)
        USE_VENV='no'
        ;;
esac

${PIP} install \
        -r "${PROJECT_DIR}ansible-requirements.txt" \
        -r "${PROJECT_DIR}molecule-requirements.txt" ${@:-}
${GALAXY} collection install -U --timeout=120 ${PROJECT_DIR}
