---
- name: Prepare
  hosts: instance
  tasks:
    - name: Create basedir
      become: true
      ansible.builtin.file:
        path: "/opt/basedir"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0755"
