---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Collect lvm information
  become: true
  ansible.builtin.setup:
    gather_subset:
      - hardware
      - mounts

- name: Extending root logical volume
  become: true
  vars:
    root_dev: "{{ (ansible_mounts | selectattr('mount', '==', '/') | first).device | default('') }}"
    root_lv: "{{ root_dev | split('/') | last | split('-') | last | default('') }}"
  community.general.lvol:
    lv: "{{ root_lv }}"
    vg: "{{ ansible_lvm.lvs[root_lv].vg }}"
    size: +100%FREE
    resizefs: true
  when:
    - ansible_lvm | default({}) != {}
    - root_lv in ansible_lvm.lvs
    - ansible_lvm.lvs[root_lv].vg is defined
  register: _extend
  until: _extend is succeeded
  retries: 5
  delay: 5
