---
- name: Disable libvirt owner remembering
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^#?remember_owner\s*='
    line: 'remember_owner = 0'
  notify: restart libvirt
