---
- name: Run command to upgrade OCP to newest subrelease
  ansible.builtin.command: >
    oc adm upgrade --to-latest=true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
  changed_when: false

- name: Wait few second to proceed OCP upgrade
  ansible.builtin.pause:
    seconds: 30

- name: Wait for upgrade to complete
  ansible.builtin.command: >
    oc adm upgrade status
  register: _update_status
  retries: 300
  delay: 10
  until: "'Update is proceeding well' not in _update_status.stdout"
  changed_when: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
