---
- name: Exclude qemu-kvm and libvirt for being upgraded
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^exclude='
    line: 'exclude=qemu-kvm,libvirt*'
    state: present
