---
driver:
  name: podman

log: true

platforms:
  - name: centos
    hostname: centos
    image: "ubi9/ubi-init"
    registry:
      url: "registry.access.redhat.com"
    command: "sleep infinity"
    privileged: true
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits:
      - host

provisioner:
  inventory:
    hosts:
      all:
        hosts:
          centos:
            ansible_python_interpreter: /usr/bin/python3
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}:${HOME}/zuul-jobs/roles:/Users/ldenny/Code/ci/upstream/ci-framework.git/wt/refresh_ci_multus/roles"
    ANSIBLE_LIBRARY: "${ANSIBLE_LIBRARY:-/usr/share/ansible/plugins/modules}"
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-/usr/share/ansible/plugins/filter}"

scenario:
  test_sequence:
    - prepare
    - converge
    - cleanup
