---
- name: Create crc logs directory
  ignore_errors: true # noqa: ignore-errors
  ansible.builtin.file:
    path: "{{ cifmw_artifacts_basedir }}/logs/crc"
    state: directory
    mode: "0755"

- name: Copy logs
  become: true
  ansible.builtin.copy:
    src: /ostree/deploy/rhcos/var/log/pods
    dest: "{{ ansible_user_dir }}/logs"
    remote_src: true

- name: Change ownership in logs
  become: true
  ansible.builtin.command: >
    chown -R {{ ansible_user }}:{{ ansible_user }} {{ ansible_user_dir }}/logs

- name: Copy logs from CRC VM
  ansible.builtin.fetch:
    src: "{{ ansible_user_dir }}/logs"
    dest: "{{ cifmw_artifacts_basedir }}/logs/crc/"
  ignore_errors: true # noqa: ignore-errors
