---
# Versions are set at group_vars/all.yml
# TODO(evallesp): We're setting pull capabilities directly from roles that are required.
# We might eventually think how to simplify reproducer and let each of the roles to clone
# repositories. Might be also a good option to use an ansible role for pulling them
# in the desired moment by cloning it.
#
# Precedence chain:
#    * Zuul repos
#    * cifmw_reproducer_repositories
#    * cifmw_reproducer_default_repositories
#    * Git pull logic in each of the roles

cifmw_reproducer_default_repositories:
  - src: "{{ cifmw_repo_url }}"
    dest: "{{ cifmw_reproducer_controller_user_dir }}/{{ cifmw_repo_relative }}"
    version: "{{ cifmw_repo_version_pin }}"
  - src: "{{ cifmw_installyamls_repo_url }}"
    dest: "{{ cifmw_reproducer_controller_user_dir }}/{{ cifmw_installyamls_repos_relative }}"
    version: "{{ cifmw_install_yamls_version_pin }}"
  - src: "{{ cifmw_architecture_repo_url }}"
    dest: "{{ cifmw_reproducer_controller_user_dir }}/{{ cifmw_architecture_repo_relative }}"
    version: "{{ cifmw_architecture_repo_version_pin }}"

# one place to rule them all
cifmw_reproducer_nm_dnsmasq: "/etc/NetworkManager/conf.d/zz-dnsmasq.conf"
cifmw_reproducer_nm_delegation: >-
  /etc/NetworkManager/dnsmasq.d/cifmw-delegate.conf
