---
- name: Kustomize ControlPlane for glance over NFS
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  vars:
    cifmw_controlplane_kustomizations_path: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane"
    cifmw_nfs_shares_glance: "{{ cifmw_nfs_shares[0] | default('glance') }}"
  tasks:
    - name: Ensure the kustomizations dir exists
      ansible.builtin.file:
        path: "{{ cifmw_controlplane_kustomizations_path }}"
        state: directory
        mode: '755'

    - name: Create kustomization to really enable a file powered by NFS as glance backend
      ansible.builtin.template:
        dest: "{{ cifmw_controlplane_kustomizations_path }}/90-glance-nfs.yaml"
        src: glance_nfs_enable_kustomize.yaml.j2
        mode: '644'
