---
- name: Kustomize ControlPlane to setup glance NFS in pre_deploy
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  vars:
    cifmw_controlplane_kustomizations_path: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane"
    glance_operator_path: "{{ cifmw_glance_operator_path|default(ansible_user_dir+'/src/github.com/openstack-k8s-operators/glance-operator') }}"
  tasks:
    - name: Ensure the kustomizations dir exists
      ansible.builtin.file:
        path: "{{ cifmw_manifests_dir }}/kustomizations/controlplane"
        state: directory
        mode: '755'

    - name: Create kustomization to setup a file-based glance backend based on a NFS share
      ansible.builtin.template:
        dest: "{{ cifmw_controlplane_kustomizations_path }}/95-setup-disabled-glance-nfs.yaml"
        src: glance_nfs_setup_kustomize.yaml.j2
        mode: '644'
