---
- name: Kustomize ControlPlane for cinder over NFS
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  vars:
    cifmw_controlplane_kustomizations_path: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane"
    cinder_operator_path: "{{ cifmw_cinder_operator_path|default(ansible_user_dir+'/src/github.com/openstack-k8s-operators/cinder-operator') }}"
    _cinder_nfs_secret_files:
      - cinder-backup-nfs-secrets.yaml
      - cinder-volume-nfs-secrets.yaml
    cifmw_nfs_shares_cinder: "{{ cifmw_nfs_shares[0] | default('cinder') }}"
    cifmw_nfs_shares_cinderbackup: "{{ cifmw_nfs_shares[1] | default('cinderbackup') }}"
  tasks:
    - name: Ensure the kustomizations dir exists
      ansible.builtin.file:
        path: "{{ cifmw_manifests_dir }}/kustomizations/controlplane"
        state: directory
        mode: '755'

    - name: Create the cinder-backup OpenStackControlPlane configuration file
      ansible.builtin.copy:
        dest: "{{ cifmw_controlplane_kustomizations_path }}/cinder-backup.yaml"
        content: |
          apiVersion: core.openstack.org/v1beta1
          kind: OpenStackControlPlane
          metadata:
            name: openstack
          spec:
            cinder:
              template:
                customServiceConfig: |
                  [DEFAULT]
                  debug = true
                cinderBackup:
                  replicas: 1
                  customServiceConfig: |
                    [DEFAULT]
                    backup_driver=cinder.backup.drivers.nfs.NFSBackupDriver
                    backup_mount_options=nosharecache
                  customServiceConfigSecrets:
                    - cinder-backup-nfs-secrets
                  networkAttachments:
                  - storage
        mode: '640'

    - name: Create the definition of the secrets
      ansible.builtin.template:
        dest: "{{ cifmw_controlplane_kustomizations_path }}/{{ item }}"
        src: "{{ item }}.j2"
        mode: '640'
      loop: "{{ _cinder_nfs_secret_files }}"

    - name: Apply the secrets
      environment:
        KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
        PATH: "{{ cifmw_path }}"
      ansible.builtin.shell: |
        oc project {{ namespace }}
        oc apply -f {{ cifmw_controlplane_kustomizations_path }}/{{ item }}
      register: apply_result
      changed_when: ('stdout' in apply_result) and ('unchanged' not in apply_result.stdout)
      failed_when: ( apply_result.rc | int ) > 1
      loop: "{{ _cinder_nfs_secret_files }}"

    - name: Create kustomization to really enable NFS shares as backends for cinder and cinder-backup
      ansible.builtin.template:
        dest: "{{ cifmw_controlplane_kustomizations_path }}/90-cinder-nfs.yaml"
        src: cinder_nfs_kustomize.yaml.j2
        mode: '640'
