---
- name: Deploy Loki for CloudKitty
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig | default(ansible_env.HOME + '/.kube/config') }}"
    PATH: "{{ cifmw_path | default(ansible_env.PATH) }}"
  tasks:
    - name: Deploy Loki operator and MinIO for CloudKitty
      ansible.builtin.import_role:
        name: deploy_loki
