---
- name: Deploy Loki for CloudKitty
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: true
  tasks:
    - name: Deploy Loki operator and MinIO for CloudKitty
      ansible.builtin.import_role:
        name: deploy_loki
