---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
- name: Apply PCI DSS settings to OpenStackControlPlane
  hosts: localhost
  gather_facts: false
  vars:
    openstackcontrolplane_name: "openstack-galera"
    openstackcontrolplane_namespace: "openstack"

    pci_dss_config: |
      [security_compliance]
      lockout_failure_attempts = 2
      lockout_duration = 5
      password_regex = ^(?=.*\d)(?=.*[a-zA-Z]).{7,}$
      unique_last_password_count = 2
      user_minimum_password_age = 0
      disable_user_account_days_inactive = 1
      password_expires_days = 90

  tasks:
    - name: Patch Keystone customServiceConfig with PCI DSS values
      kubernetes.core.k8s:
        kubeconfig: "{{ cifmw_openshift_kubeconfig }}"
        state: present
        definition:
          apiVersion: core.openstack.org/v1beta1
          kind: OpenStackControlPlane
          metadata:
            name: "{{ openstackcontrolplane_name }}"
            namespace: "{{ openstackcontrolplane_namespace }}"
          spec:
            keystone:
              enabled: true
              template:
                databaseInstance: openstack
                secret: osp-secret
                customServiceConfig: "{{ pci_dss_config }}"
