---
#
# Playbook that utilizes the Performance Co-Pilot toolkit
# to collect system metrics and generate figures for analysis.
# Relies on the corresponding `pcp_metrics` Ansible role.
#
# The best place to call this hook is under post_tests actions.
#
- name: Collect performance metrics
  hosts: all,!localhost
  gather_facts: false
  tasks:
    - name: Gather metrics
      ansible.builtin.include_role:
        name: pcp_metrics
        tasks_from: gather


- name: Process metrics
  hosts: localhost
  tasks:
    # TODO: annotations
    - name: '[TODO] Annotations'
      ansible.builtin.shell: >-
        find "{{ ansible_user_dir }}" -iname 'ansible-deploy-edpm.log';
        find "{{ ansible_user_dir }}" -iname 'ansible-deploy-architecture.log';
        find "{{ ansible_user_dir }}" -iname 'ansible-post-deployment.log';

        grep -e 'PLAY \[' -e 'TASK \[kustomize_deploy : Apply generated content for' $(find . -iname 'ansible-deploy-architecture.log' 2>/dev/null);

        grep -e 'PLAY \[' -e 'TASK \[test_operator : Run' $(find . -iname 'ansible-post-deployment.log' 2>/dev/null | head -n 1);
      ignore_errors: true
      changed_when: false
      register: _shell

    - name: '[TODO] Annotations'
      debug:
        msg: "{{ _shell }}"
      ignore_errors: true

    - name: Generate figures
      ansible.builtin.include_role:
        name: pcp_metrics
        tasks_from: plot

    - name: Copy metrics to ci-framework-data
      ansible.builtin.copy:
        src: /tmp/pcp-metrics/
        dest: "{{ ansible_user_dir }}/ci-framework-data/metrics"
        mode: preserve


- name: Process metrics (check)
  hosts: controller
  tasks:
    - name: Copy metrics to ci-framework-data
      ansible.builtin.copy:
        src: /tmp/pcp-metrics/
        dest: "{{ ansible_user_dir }}/ci-framework-data/metrics"
        mode: preserve
