---
#
# Playbook that setups the Performance Co-Pilot toolkit on infra.
# Relies on the corresponding `pcp_metrics` Ansible role.
#
# The best place to call this hook is under post_infra actions.
#
- name: Start collecting performance metrics
  # hosts: computes,controllers,hypervisors
  hosts: all,!localhost
  gather_facts: false
  tasks:
    - name: Setup PCP
      ansible.builtin.include_role:
        name: pcp_metrics
        tasks_from: setup
