---
- name: Run Rally benchmarks
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Run rally role
      ansible.builtin.include_role:
        name: rally
