---
- name: Store stestr timing data in internal repository
  hosts: localhost
  gather_facts: false
  vars:
    repo_path: "/tmp/timing-data"
    timing_data_repo: "https://user:{{ git_token }}@gitlab.cee.redhat.com/ci-framework/timing-data"
  tasks:
    - name: Clone timing data repository
      ansible.builtin.git:
        repo: "{{ timing_data_repo }}"
        dest: "{{ repo_path }}"
        version: "main"

    - name: Configure git settings
      community.general.git_config:
        repo: "{{ repo_path }}"
        scope: local
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - {name: 'user.name', value: 'Zuul'}
        - {name: 'user.email', value: 'rhos-dfg-ciops@redhat.com'}
        - {name: 'remote.origin.url', value: '{{ timing_data_repo }}'}

    - name: Find all 'tempest' directories
      ansible.builtin.find:
        paths: "{{ ansible_user_dir }}/ci-framework-data/tests/test_operator/"
        file_type: directory
        patterns: "*-tempest*"
      register: tempest_dirs

    - name: Loop over 'tempest' directories
      ansible.builtin.debug:
        msg: "DIR: {{ item.path }}"
      loop: "{{ tempest_dirs.files }}"

    - name: Store timing data for every tempest-test directory
      ansible.builtin.include_tasks: tempest_store_timing_data_each.yaml
      vars:
        timing_data_repo_dir: "{{ repo_path }}/{{ job_name }}/{{ tempest_tests_name.path | basename }}"
        stestr_tar_path: "ci-framework-data/tests/test_operator/{{ tempest_tests_name.path | basename }}/stestr.tar.gz"
      loop: "{{ tempest_dirs.files }}"
      loop_control:
        loop_var: tempest_tests_name
