---
- name: Update container-selinux on ceph target nodes
  hosts: "{{ cifmw_ceph_target | default('computes') }}"
  gather_facts: false
  become: true
  tasks:
    - name: Update container-selinux to latest available version
      ansible.builtin.dnf:
        name: container-selinux
        state: latest

    - name: Show container-selinux version
      ansible.builtin.command:
        cmd: rpm -q container-selinux
      changed_when: false
