---
# Example usage:
# ansible-playbook \
#   -e @secrets.yaml -e @scenarios/reproducers/va-hci-minimal-sno.yml \
#   -i inventory.yaml \
#   example-playbook.yaml
- name: Deploying SNO host
  hosts: sno.dev
  gather_facts: true
  tasks:
    - name: Run devscript sno
      ansible.builtin.include_role:
        name: devscripts_sno
