- name: Pin OpenSSL to 3.5.5
  become: true
  register: _cifmw_pin_openssl
  changed_when: >-
    _cifmw_pin_openssl.rc == 0 and
    "Nothing to do." not in (_cifmw_pin_openssl.stdout | default(""))
  failed_when: false
  ansible.builtin.command:
    argv:
      - dnf
      - downgrade
      - --allowerasing
      - -y
      - openssl-3.5.5
      - openssl-libs-3.5.5
